#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Regenerate ../nyamp_unicode_tables.inc.

The pre-tokenizer regex of the model uses \\p{L}, \\p{N} and \\s.  HuggingFace
`tokenizers` evaluates them with Oniguruma, whose Unicode version is neither
the one of the local Python nor the one of any libc.  Deriving the classes
from a Unicode data file would therefore be *almost* right, and "almost" shows
up as a token mismatch on a rare CJK extension character months later.

So the classes are measured, not looked up: every code point is pushed through
the reference library's own regex engine and the matching set is written out
as sorted ranges.  Run this with the same `tokenizers` wheel that produces the
golden files (tests/gen_golden.py) whenever that wheel is upgraded.

The fourth table is Python's str.isprintable(), needed only because the chat
template prints nested tool-call arguments with Python repr().

Usage: python gen_unicode_tables.py > ../nyamp_unicode_tables.inc
"""

import sys
import unicodedata

import tokenizers
from tokenizers import Regex, pre_tokenizers

ALL = [c for c in range(0x110000) if not 0xD800 <= c <= 0xDFFF]


def onig_class(pattern):
    text = "".join(map(chr, ALL))
    split = pre_tokenizers.Split(Regex(pattern), behavior="removed")
    rest = set()
    for piece, _ in split.pre_tokenize_str(text):
        rest.update(map(ord, piece))
    return [c for c in ALL if c not in rest]


def ranges(code_points):
    out = []
    for c in code_points:
        if out and out[-1][1] == c - 1:
            out[-1][1] = c
        else:
            out.append([c, c])
    return out


def emit(name, comment, code_points):
    table = ranges(code_points)
    print(f"// {comment}: {len(code_points)} code points, {len(table)} ranges")
    print(f"static const uint32_t {name}[][2] = {{")
    line = " "
    for lo, hi in table:
        item = f" {{0x{lo:X}, 0x{hi:X}}},"
        if len(line) + len(item) > 78:
            print(line)
            line = " "
        line += item
    print(line)
    print("};\n")


def main():
    print("// SPDX-License-Identifier: Apache-2.0")
    print("//")
    print("// GENERATED by tests/gen_unicode_tables.py - do not edit.")
    print(f"// Source: tokenizers {tokenizers.__version__} (Oniguruma) for the")
    print("// regex classes, Python "
          f"{sys.version.split()[0]} / Unicode {unicodedata.unidata_version}")
    print("// for str.isprintable().  Derived from the Unicode Character")
    print("// Database (Unicode License v3); no model data is involved.\n")
    emit("kUnicodeLetter", "Oniguruma \\p{L}", onig_class(r"\p{L}"))
    emit("kUnicodeNumber", "Oniguruma \\p{N}", onig_class(r"\p{N}"))
    emit("kUnicodeSpace", "Oniguruma \\s", onig_class(r"\s"))
    # Only the non-ASCII part matters; ASCII is handled inline by the caller.
    emit("kPythonNonPrintable", "not str.isprintable(), above U+007F",
         [c for c in ALL if c > 0x7F and not chr(c).isprintable()])


if __name__ == "__main__":
    main()
