#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0

"""Generate the fixed-size LVGL font subsets used by the eye scenes."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import urllib.request
from pathlib import Path


FONT_MATRIX = {
    "title": ("AlimamaShuHeiTi.ttf", (20, 28, 42)),
    "body": ("MiSans-Semibold.ttf", (14, 18)),
    "english": ("Tinos-Bold.ttf", (18, 42, 72, 96, 119)),
}

NOTO_FILENAME = "NotoSansCJKsc-Bold.otf"
NOTO_REVISION = "f8d157532fbfaeda587e826d4cd5b21a49186f7c"
NOTO_URL = (
    "https://raw.githubusercontent.com/notofonts/noto-cjk/"
    f"{NOTO_REVISION}/Sans/OTF/SimplifiedChinese/{NOTO_FILENAME}"
)
NOTO_SHA256 = "b5f0d1a190a7f9b43c310a8850630af12553df32c4c050543f9059732d9b4c0a"
CONVERTER = "lv_font_conv@1.5.3"


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def download_fallback(directory):
    directory.mkdir(parents=True, exist_ok=True)
    target = directory / NOTO_FILENAME
    if target.is_file() and sha256(target) == NOTO_SHA256:
        return target
    request = urllib.request.Request(NOTO_URL, headers={"User-Agent": "Nyabula-fonts"})
    with urllib.request.urlopen(request, timeout=60) as response:
        data = response.read(32 * 1024 * 1024 + 1)
    if hashlib.sha256(data).hexdigest() != NOTO_SHA256:
        raise ValueError("Noto Sans download does not match the pinned SHA-256")
    temporary = target.with_suffix(".download")
    temporary.write_bytes(data)
    temporary.replace(target)
    return target


def select_font(font_dir, filename, fallback):
    original = font_dir / filename
    if original.is_file():
        return original
    if fallback.is_file():
        return fallback
    raise FileNotFoundError(
        f"Missing {filename} and Noto Sans fallback. Supply --fallback-font "
        "or use --download-fallback."
    )


def collect_symbols(paths):
    content = "".join(
        path.read_text(encoding="utf-8")
        for path in paths
    )
    return "".join(sorted({
        char for char in content
        if "\u3400" <= char <= "\u9fff" or char in "，。！？·℃°"
    }))


def sanitize_metadata(output):
    lines = output.read_text(encoding="utf-8").splitlines()
    while lines and not lines[-1]:
        lines.pop()
    lines = [
        " * Generated by app/nyabula/tools/generate_fonts.py."
        if line.startswith(" * Opts:") else line
        for line in lines
    ]
    output.write_text("/* clang-format off */\n" + "\n".join(lines) + "\n",
                      encoding="utf-8", newline="\n")


def generate(font_dir, output_dir, fallback, html=None):
    app_dir = Path(__file__).resolve().parents[1]
    sources = [html] if html else []
    sources.extend(sorted((app_dir / "src").glob("*.c")))
    sources.extend(sorted((app_dir / "include").rglob("*.h")))
    symbols = collect_symbols(sources)
    selected = {
        family: select_font(font_dir, filename, fallback)
        for family, (filename, _) in FONT_MATRIX.items()
    }
    manifest = {
        "converter": CONVERTER,
        "symbols_sha256": hashlib.sha256(symbols.encode()).hexdigest(),
        "fonts": {
            family: {"file": path.name, "sha256": sha256(path),
                     "sizes": list(FONT_MATRIX[family][1])}
            for family, path in selected.items()
        },
    }
    manifest_path = output_dir / "font-manifest.json"
    outputs = [output_dir / f"nyabula_font_{family}_{size}.c"
               for family, (_, sizes) in FONT_MATRIX.items() for size in sizes]
    if manifest_path.is_file() and all(path.is_file() for path in outputs):
        if json.loads(manifest_path.read_text(encoding="utf-8")) == manifest:
            print("Eye glyph tables are up to date")
            return
    converter = shutil.which("npx.cmd") or shutil.which("npx")
    if converter is None:
        raise FileNotFoundError("npx")
    converter_env = os.environ.copy()
    converter_env.setdefault("NODE_OPTIONS", "--max-old-space-size=512")
    output_dir.mkdir(parents=True, exist_ok=True)
    for family, (filename, sizes) in FONT_MATRIX.items():
        font = selected[family]
        print(f"Eye {family}: {font.name}", flush=True)
        for size in sizes:
            name = f"nyabula_font_{family}_{size}"
            output = output_dir / f"{name}.c"
            command = [
                converter, "--yes", "--registry=https://registry.npmjs.org/",
                CONVERTER,
                "--font", str(font),
                "-r", "0x20-0x7e",
            ]
            if family != "english":
                command.extend(["--symbols", symbols])
            else:
                command.extend(["--symbols", "°"])
            command.extend([
                "--size", str(size),
                "--bpp", "4",
                "--no-compress",
                "--format", "lvgl",
                "--lv-include", "lvgl/lvgl.h",
                "--lv-font-name", name,
                "-o", str(output),
            ])
            subprocess.run(command, check=True, env=converter_env)
            sanitize_metadata(output)
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n",
                             encoding="utf-8", newline="\n")


def main():
    parser = argparse.ArgumentParser()
    app_dir = Path(__file__).resolve().parents[1]
    parser.add_argument("--font-dir", type=Path, default=app_dir / "res/fonts")
    parser.add_argument("--output-dir", type=Path,
                        default=app_dir / "src/generated/fonts")
    parser.add_argument("--fallback-font", type=Path)
    parser.add_argument("--download-fallback", action="store_true",
                        help="Fetch pinned Noto Sans from its official repository")
    parser.add_argument("--html", type=Path,
                        help="Optional extra text source for the glyph subset")
    args = parser.parse_args()
    fallback = args.fallback_font or args.font_dir / NOTO_FILENAME
    missing = any(not (args.font_dir / name).is_file()
                  for name, _ in FONT_MATRIX.values())
    if args.download_fallback and missing and args.fallback_font is None:
        fallback = download_fallback(args.font_dir)
    generate(args.font_dir, args.output_dir, fallback, args.html)


if __name__ == "__main__":
    main()
