#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0

"""Generate the fixed-size LVGL font subsets used by the eye scenes."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import urllib.request
from pathlib import Path


FONT_MATRIX = {
    "title": ("AlimamaShuHeiTi.ttf", (20, 28, 42)),
    "body": ("MiSans-Semibold.ttf", (14, 18)),
    "english": ("Tinos-Bold.ttf", (18, 42, 72, 96, 119)),
}

# Text that arrives at run time -- a reply, a track name, an alarm label, a
# notification -- is drawn in these sizes, and no scan of the sources can know
# which characters it will need.  They carry both levels of GB 2312 (6763
# characters) instead.  42 px only shows the fixed words of the scenes.
RUNTIME_TEXT = {
    ("body", 14): 2, ("body", 18): 2, ("title", 20): 2, ("title", 28): 2,
}
# A glyph a table lacks is taken from the next one rather than drawn as a box:
# a title in the wrong weight still reads, a row of boxes does not.  The chain
# ends at body 18, the widest table of the widest font.
FALLBACK = {
    ("title", 42): ("title", 28), ("title", 28): ("body", 18),
    ("title", 20): ("body", 18), ("body", 14): ("body", 18),
}
# CJK punctuation and the full-width forms, as ranges.
RUNTIME_RANGES = ("0x2010-0x2027", "0x3000-0x303f", "0xff01-0xff5e")

NOTO_FILENAME = "NotoSansCJKsc-Bold.otf"
NOTO_REVISION = "f8d157532fbfaeda587e826d4cd5b21a49186f7c"
NOTO_URL = (
    "https://raw.githubusercontent.com/notofonts/noto-cjk/"
    f"{NOTO_REVISION}/Sans/OTF/SimplifiedChinese/{NOTO_FILENAME}"
)
NOTO_SHA256 = "b5f0d1a190a7f9b43c310a8850630af12553df32c4c050543f9059732d9b4c0a"
CONVERTER = "lv_font_conv@1.5.3"


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def download_fallback(directory):
    directory.mkdir(parents=True, exist_ok=True)
    target = directory / NOTO_FILENAME
    if target.is_file() and sha256(target) == NOTO_SHA256:
        return target
    request = urllib.request.Request(NOTO_URL, headers={"User-Agent": "Nyabula-fonts"})
    with urllib.request.urlopen(request, timeout=60) as response:
        data = response.read(32 * 1024 * 1024 + 1)
    if hashlib.sha256(data).hexdigest() != NOTO_SHA256:
        raise ValueError("Noto Sans download does not match the pinned SHA-256")
    temporary = target.with_suffix(".download")
    temporary.write_bytes(data)
    temporary.replace(target)
    return target


def select_font(font_dir, filename, fallback):
    original = font_dir / filename
    if original.is_file():
        return original
    if fallback.is_file():
        return fallback
    raise FileNotFoundError(
        f"Missing {filename} and Noto Sans fallback. Supply --fallback-font "
        "or use --download-fallback."
    )


def collect_symbols(paths):
    content = "".join(
        path.read_text(encoding="utf-8")
        for path in paths
    )
    return "".join(sorted({
        char for char in content
        if "\u3400" <= char <= "\u9fff" or char in "，。！？·℃°"
    }))


def gb2312(levels):
    """The hanzi of GB 2312: level 1 is rows 16-55, level 2 rows 56-87."""
    last = 0xD7 if levels == 1 else 0xF7
    chars = []
    for high in range(0xB0, last + 1):
        for low in range(0xA1, 0xFF):
            try:
                chars.append(bytes((high, low)).decode("gb2312"))
            except UnicodeDecodeError:
                pass  # The five unassigned cells at the end of row 55.
    return "".join(chars)


def sanitize_metadata(output):
    lines = output.read_text(encoding="utf-8").splitlines()
    while lines and not lines[-1]:
        lines.pop()
    lines = [
        " * Generated by app/nyabula/tools/generate_fonts.py."
        if line.startswith(" * Opts:") else line
        for line in lines
    ]
    output.write_text("/* clang-format off */\n" + "\n".join(lines) + "\n",
                      encoding="utf-8", newline="\n")


def generate(font_dir, output_dir, fallback, html=None):
    app_dir = Path(__file__).resolve().parents[1]
    sources = [html] if html else []
    sources.extend(sorted((app_dir / "src").glob("*.c")))
    sources.extend(sorted((app_dir / "include").rglob("*.h")))
    symbols = collect_symbols(sources)
    selected = {
        family: select_font(font_dir, filename, fallback)
        for family, (filename, _) in FONT_MATRIX.items()
    }
    manifest = {
        "converter": CONVERTER,
        "symbols_sha256": hashlib.sha256(symbols.encode()).hexdigest(),
        "runtime_text": {f"{family}_{size}": levels
                         for (family, size), levels in RUNTIME_TEXT.items()},
        "runtime_ranges": list(RUNTIME_RANGES),
        "fallback": {f"{a}_{b}": f"{c}_{d}"
                     for (a, b), (c, d) in FALLBACK.items()},
        "fonts": {
            family: {"file": path.name, "sha256": sha256(path),
                     "sizes": list(FONT_MATRIX[family][1])}
            for family, path in selected.items()
        },
    }
    manifest_path = output_dir / "font-manifest.json"
    outputs = [output_dir / f"nyabula_font_{family}_{size}.c"
               for family, (_, sizes) in FONT_MATRIX.items() for size in sizes]
    if manifest_path.is_file() and all(path.is_file() for path in outputs):
        if json.loads(manifest_path.read_text(encoding="utf-8")) == manifest:
            print("Eye glyph tables are up to date")
            return
    # npx.cmd runs through cmd.exe, whose 8191 character command line cannot
    # carry a GB 2312 symbol list.  An installed lv_font_conv.js is started
    # with node directly instead, which has the 32 K limit of CreateProcess.
    local = os.environ.get("NYABULA_LV_FONT_CONV")
    if local:
        prefix = [shutil.which("node") or "node", local]
    else:
        converter = shutil.which("npx.cmd") or shutil.which("npx")
        if converter is None:
            raise FileNotFoundError("npx")
        prefix = [converter, "--yes",
                  "--registry=https://registry.npmjs.org/", CONVERTER]
    converter_env = os.environ.copy()
    converter_env.setdefault("NODE_OPTIONS", "--max-old-space-size=512")
    output_dir.mkdir(parents=True, exist_ok=True)
    for family, (filename, sizes) in FONT_MATRIX.items():
        font = selected[family]
        print(f"Eye {family}: {font.name}", flush=True)
        for size in sizes:
            name = f"nyabula_font_{family}_{size}"
            output = output_dir / f"{name}.c"
            command = prefix + [
                "--font", str(font),
                "-r", "0x20-0x7e",
            ]
            if (family, size) in RUNTIME_TEXT:
                wide = "".join(sorted(
                    set(symbols) | set(gb2312(RUNTIME_TEXT[(family, size)]))))
                for span in RUNTIME_RANGES:
                    command.extend(["-r", span])
                command.extend(["--symbols", wide])
            elif family != "english":
                command.extend(["--symbols", symbols])
            else:
                command.extend(["--symbols", "°"])
            if (family, size) in FALLBACK:
                command.extend(["--lv-fallback", "nyabula_font_%s_%d"
                                % FALLBACK[(family, size)]])
            command.extend([
                "--size", str(size),
                "--bpp", "4",
                "--no-compress",
                "--format", "lvgl",
                "--lv-include", "lvgl/lvgl.h",
                "--lv-font-name", name,
                "-o", str(output),
            ])
            subprocess.run(command, check=True, env=converter_env)
            sanitize_metadata(output)
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n",
                             encoding="utf-8", newline="\n")


def main():
    parser = argparse.ArgumentParser()
    app_dir = Path(__file__).resolve().parents[1]
    parser.add_argument("--font-dir", type=Path, default=app_dir / "res/fonts")
    parser.add_argument("--output-dir", type=Path,
                        default=app_dir / "src/generated/fonts")
    parser.add_argument("--fallback-font", type=Path)
    parser.add_argument("--download-fallback", action="store_true",
                        help="Fetch pinned Noto Sans from its official repository")
    parser.add_argument("--html", type=Path,
                        help="Optional extra text source for the glyph subset")
    args = parser.parse_args()
    fallback = args.fallback_font or args.font_dir / NOTO_FILENAME
    missing = any(not (args.font_dir / name).is_file()
                  for name, _ in FONT_MATRIX.values())
    if args.download_fallback and missing and args.fallback_font is None:
        fallback = download_fallback(args.font_dir)
    generate(args.font_dir, args.output_dir, fallback, args.html)


if __name__ == "__main__":
    main()
