export const CAPABILITY_LABELS: Record<string, string> = {
  'eye-expression': '猫猫表情',
  'core-read': 'Core 只读工具', 'core-write': 'Core 写入与设备控制', 'file-shell': '文件与 Shell',
  'web-search-fetch-weather': '搜索、网页与天气', 'device-sensors': '设备与传感器', music: '音乐控制',
  skills: 'Skills', 'skill-sync': 'Skill 同步', 'memory-persona': '人格与主人资料',
  'cron-heartbeat': '自动化与主动检查', 'voice-asr-tts': '语音识别与合成', 'vision-camera': '视觉与相机',
  'mcp-client': 'MCP · 连接外部服务', 'mcp-server': 'MCP · 允许外部访问', 'openclaw-node': 'OpenClaw 节点',
  feishu: '飞书', weixin: '微信', mqtt: 'MQTT', 'ble-gatt': '蓝牙 GATT', 'ble-network': '蓝牙网络',
  'lvgl-channel': 'LVGL 渠道', 'rest-diagnostics': 'REST 诊断', quickapp: 'QuickApp',
  'web-cli': 'Web 与本地 CLI', 'model-router': '模型与路由',
};
export const CAPABILITY_REASONS: Record<string, string> = {
  core_signed_openclaw_node: '签名设备身份、Gateway 配对和 Core 命令；当前为节点客户端，不是 Gateway 服务端',
  core_feishu_channel: '飞书应用机器人长连接、文字收发与持久会话；需配置应用并手动启动',
  core_weixin_channel: '微信扫码登录、文字收发与持久会话；需真实平台账号，手动启动通道',
  core_workspace_tools: '工作目录读写与上游 Shell；写入和命令执行进入任务审批，实际命令取决于固件',
  core_network_tools: '搜索、新闻、天气与 HTTPS 网页；搜索和新闻需配置服务密钥',
  core_eye_expression: '对话可调用真实 Eye 表情服务；只变表情，无机械动作，不重复询问确认',
  core_owner_mqtt_channel: '主人配置的 MQTT 消息进入统一执行记录；需手动启动并连接 Broker',
  core_scoped_mcp_2025: 'MCP 2025-11-25 外连；目录逐项授权，每次调用均需批准',
  core_scoped_mcp_in_readonly: '独立凭据与只读范围；默认关闭，仅本机或可信隧道，未开放外部聊天',
  core_scoped_mcp_in: '独立凭据、只读范围与隔离对话；默认关闭，仅本机或可信隧道，对话使用设备模型账户',
  owner_managed_guidance: '主人管理与启停；正文只提供指导，不增加权限',
  core_durable_scheduler: '设备端持久调度；每次执行进入统一运行记录与审批',
  owner_only: '仅主人可用', approval_adapter_required: '等待写入审批适配',
  per_action_owner_approval: '每个写操作均需主人单次批准',
  restricted_by_core_policy: 'Core 策略未授权，不向普通聊天开放',
  provider_credentials_required: '需要服务配置与授权', hardware_provider_required: '需要实际硬件服务',
  audio_provider_required: '需要音频服务和后端配置', management_adapter_required: '管理接口尚未接入',
  profile_adapter_required: '资料管理接口尚未接入', scheduler_adapter_required: '自动化调度接口尚未接入',
  authorization_adapter_required: '需要接入独立认证与权限', protected_endpoint_required: '需要受保护的访问端点',
  not_compiled: '当前固件未编译此能力', channel_credentials_required: '需要渠道凭据与授权范围',
  synchronization_policy_required: '需要同步来源和更新授权策略', display_provider_required: '需要实际显示服务',
  quickapp_runtime_required: '需要 QuickApp 运行环境', core_authenticated_transport: '使用 Core 认证入口',
  model_configuration_required: '需要配置可用模型',
  core_model_router: '设备多模型配置、路由策略与运行统计；需先配置可用后端',
  core_profile_context: '猫猫名称、主人称呼、语言、语气与自定义偏好进入真实对话上下文',
};
