#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# tools/setup_workspace.sh — wire this repository into an openvela workspace
# exactly the way the repo manifest (contest2026_062_PharosTech.xml
# <linkfile> entries) does, without needing `repo sync`.
#
# Usage (from the openvela workspace root that already contains
# nuttx/ apps/ packages/ external/ prebuilts/ ...):
#
#   contest2026_062_PharosTech/tools/setup_workspace.sh [repo_dir]
#
# Idempotent: re-running only refreshes the symlinks. It also drops any
# autogenerated apps/**/Kconfig that still points at another checkout so
# `make context` regenerates them for this tree.

set -Eeuo pipefail

WS=$(pwd)
REPO=${1:-"$WS/contest2026_062_PharosTech"}
REPO=$(cd "$REPO" && pwd)
MANIFEST="$REPO/contest2026_062_PharosTech.xml"

[ -f "$WS/build.sh" ] || { echo "run from the openvela workspace root (build.sh missing)" >&2; exit 1; }
[ -f "$MANIFEST" ] || { echo "manifest not found: $MANIFEST" >&2; exit 1; }

link() { # src(dest-relative to repo) dest(relative to workspace)
  local src="$REPO/$1" dest="$WS/$2"
  mkdir -p "$(dirname "$dest")"
  if [ -e "$dest" ] && [ ! -L "$dest" ]; then
    echo "skip (real path exists): $2" >&2; return
  fi
  ln -sfn "$src" "$dest"
  printf '  %-45s -> %s\n' "$2" "$1"
}

echo "workspace: $WS"
echo "repo:      $REPO"

# vendor/rockchip is the board/chip root referenced by CONFIG_ARCH_*_CUSTOM_DIR
mkdir -p "$WS/vendor"
ln -sfn "$REPO" "$WS/vendor/rockchip"
printf '  %-45s -> %s\n' "vendor/rockchip" "(repo)"

# every <linkfile src=".." dest=".."/> in the manifest
while read -r src dest; do
  [ -n "$src" ] || continue
  case "$dest" in
    vendor/rockchip/*) ;;            # covered by the vendor/rockchip link
    *) link "$src" "$dest" ;;
  esac
done < <(sed -n 's/.*<linkfile src="\([^"]*\)" dest="\([^"]*\)".*/\1 \2/p' "$MANIFEST")

# stale autogenerated Kconfig files hard-code absolute paths of the tree
# they were generated in; remove them if they point elsewhere.
for f in "$WS"/apps/Kconfig "$WS"/apps/*/Kconfig "$WS"/packages/Kconfig "$WS"/packages/*/Kconfig; do
  [ -f "$f" ] || continue
  if grep -q "autogenerated" "$f" && ! grep -q "\"$WS/" "$f"; then
    rm -f "$f"; echo "  removed stale $f"
  fi
done

# apps/ and packages/ patches nyabula_core depends on (idempotent: skipped
# when already applied). See patches/README.md.
for pf in "$REPO"/patches/apps-*.patch; do
  [ -f "$pf" ] || continue
  if patch -d "$WS/apps" -p1 -N --dry-run -s < "$pf" >/dev/null 2>&1; then
    patch -d "$WS/apps" -p1 -N -s < "$pf" && echo "  applied $(basename "$pf") -> apps/"
  else
    echo "  (already applied or conflict) $(basename "$pf")"
  fi
done
for pf in "$REPO"/patches/packages-ai_agent-*.patch; do
  [ -f "$pf" ] || continue
  if patch -d "$WS/packages/ai_agent" -p1 -N --dry-run -s < "$pf" >/dev/null 2>&1; then
    patch -d "$WS/packages/ai_agent" -p1 -N -s < "$pf" && echo "  applied $(basename "$pf") -> packages/ai_agent/"
  else
    echo "  (already applied or conflict) $(basename "$pf")"
  fi
done

# generated eye fonts are gitignored (need lv_font_conv + font downloads)
FONTS="$REPO/app/nyabula/src/generated/fonts"
if ! ls "$FONTS"/nyabula_font_*.c >/dev/null 2>&1; then
  echo "  WARNING: $FONTS has no nyabula_font_*.c - run app/nyabula/tools/generate_fonts.py"
  echo "           or copy them from a previous build; the final link needs them."
fi

# firmware blobs are gitignored; remind the operator
FW="$REPO/drivers/drivers/sv6621/firmware"
for f in SWT6621S_IRAM_SDIO.bin SWT6621S_DRAM_SDIO.bin SWT6621S_NV_SDIO_ALONE.bin SWT6621S_SEEKWAVE_R00001.bin sv6160lite.nvbin; do
  [ -f "$FW/$f" ] || echo "  WARNING: missing $FW/$f (see firmware/README.md)"
done

echo "done. next: ./build.sh contest2026_062_PharosTech/configs/product -j8"
